// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package aboutme

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/loggerboy9325/website-go-htmx-temple/view/layout"

func Aboutme() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"max-w-2xl mb-20 w-full mx-auto mt-8\"><h1 class=\"text-2xl text-center font-semibold border-b border-primary pb-2\">About Me</h1><p class=\"mt-8 text-xl\">Hello! I'm George Wettlaufer, a junior tech enthusiast with a strong foundation in Amazon Web Services (AWS). I am passionate about cloud computing and eager to grow my skills and knowledge in this dynamic field. I have been working with Amazon Web Services, learning how to manage cloud infrastructure and deploy scalable solutions. My experience with AWS has given me a solid understanding of creating secure, efficient, and cost-effective cloud environments.<br>I am proficient in services such as EC2, S3, RDS, and Lambda, and I am constantly expanding my knowledge of the AWS ecosystem. I believe in continuous learning and staying updated with the latest industry trends. My approach is collaborative and detail-oriented, always aiming for excellence in every project I undertake. Outside of my professional interests, I enjoy running, coding, anything with computers. These activities keep me balanced and inspired. Get in Touch I'm always open to new opportunities and collaborations. Feel free to reach out to me or connect with me on LinkedIn, GitHub, or other platforms.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.App(true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
