// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navigation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\" text-center shadow-lg shadow-primary bg-base-100 justify-center text-primary border-b border-primary mx-auto \"><a href=\"/\" class=\"btn btn-ghost shadow-gray-700 text-2xl \">Home</a> <a href=\"/about-me\" class=\"btn btn-ghost text-2xl\">About Me</a> <a href=\"/resume\" class=\"btn btn-ghost text-2xl\">Resume</a> <a href=\"/contact-form\" class=\"btn btn-ghost text-2xl\">Contact Me</a> <a href=\"/blog\" class=\"btn btn-ghost text-2xl\">Blog</a> <a href=\"/website-info\" class=\"btn btn-ghost text-2xl\">Website Info</a> <a class=\"btn btn-ghost text-2xl\" href=\"./../../public/Resume1.pdf\" download=\"Resume.pdf\">Download Resume</a> <a class=\" text-2xl font-semibold\">Visitors: </a> <span class=\"font-semibold text-2xl\" id=\"visit\"></span><script type=\"text/javascript\">\n    const getvisitors = async () => {\n      try {\n        const url =\n          \"https://liz7p9d3mf.execute-api.us-east-1.amazonaws.com/example/MyDemoResource\";\n        const res = await fetch(url);\n        console.log(res.ok);\n        const data = await res.json();\n        console.log(data);\n        body = data.visitor;\n        document.getElementById(\"visit\").insertAdjacentHTML(\"afterbegin\", body);\n      } catch (err) {\n        console.error(err);\n      }\n    };\n\n    getvisitors();\n\n\n  </script></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
